version: '3.8'

services:
  meetsounds:
    build:
      context: ./backend  # Correcta ubicación del contexto de construcción
      dockerfile: Dockerfile
    container_name: meetsounds-app
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
